export const ALLOWANCE_CODES = Object.freeze({
  DA: 'DA',
  HRA: 'HRA',
  TRANSPORT_ALLOWANCE: 'TRANSPORT_ALLOWANCE',
  CUSTOM: 'CUSTOM',
})

export const ALLOWANCE_SOURCE_TYPES = Object.freeze({
  SYSTEM_RULE: 'SYSTEM_RULE',
  USER_DEFINED: 'USER_DEFINED',
})

export const ALLOWANCE_CALCULATION_TYPES = Object.freeze({
  FIXED_AMOUNT: 'FIXED_AMOUNT',
  FIXED_MONTHLY: 'FIXED_MONTHLY',
  PERCENTAGE_OF_BASIC: 'PERCENTAGE_OF_BASIC',
  PERCENTAGE_OF_BASIC_PLUS_DA: 'PERCENTAGE_OF_BASIC_PLUS_DA',
  MANUAL_MONTHLY_AMOUNT: 'MANUAL_MONTHLY_AMOUNT',
  RULE_LOOKUP: 'RULE_LOOKUP',
  DEPENDENT_ALLOWANCE: 'DEPENDENT_ALLOWANCE',
  SLAB_BASED: 'SLAB_BASED',
  PER_DAY: 'PER_DAY',
  PERCENTAGE_OF_CUSTOM_BASE: 'PERCENTAGE_OF_CUSTOM_BASE',
})

export const ALLOWANCE_STATUSES = Object.freeze({
  RESOLVED: 'RESOLVED',
  PARTIALLY_RESOLVED: 'PARTIALLY_RESOLVED',
  UNRESOLVED: 'UNRESOLVED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
})

export const ALLOWANCE_DEFINITION_STATUSES = Object.freeze({
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PROVISIONAL: 'PROVISIONAL',
})
